# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Covid-19DiagnosisSupport' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Xcode 11.2.1 BUG do not permit this without dev account  #use_frameworks!

  # Pods for Covid-19DiagnosisSupport
  pod "Macaw", "0.9.5"
end
